Header    header
string    time
string    local_time
string    server_time
float64   temperature

float64   pressure
float64   altitude

float64   longitude
float64   latitude

float64   ax
float64   ay
float64   az

float64   anglex
float64   angley
float64   anglez

float64   wx
float64   wy
float64   wz

float64   hx
float64   hy
float64   hz

float64   gps_height
float64   gps_yaw
float64   ground_velocity

int32     sn
float64   pdop
float64   hdop
float64   vdop
